# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=java      
runtime: java17
# Run `gradlew :web:status-history:appengineStage` to see the contents in `build/staged-app/`.
entrypoint: bin/status-history
env_variables:
  STATUS_HISTORY_OPTS: "-Dmicronaut.environments=production"

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
