micronaut:

  server:
    port: ${PORT:8080}

  router:
    static-resources:
      default:
        mapping: "/static/**"
        paths: classpath:public/static

  http:
    services:
      github:
        url: https://api.github.com

  codec:
    json:
      additional-types:
        - application/vnd.github.v3+json

github:
  feedback-repository:
    organization: TWiStErRob
    repo: net.twisterrob.travel
