insert into Section(_id, name) values('RS_1-BAK-_-y05-2-O-3', 'Elephant & Castle - Harrow & Wealdstone Station');
insert into Section(_id, name) values('RS_1-BAK-_-y05-2-I-13', 'Harrow & Wealdstone Station - Elephant & Castle');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-O-3', 'West Ruislip - Epping');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-O-12', 'Ealing Broadway - Epping');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-O-24', 'West Ruislip - Grange Hill');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-O-28', 'Woodford - Hainault');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-O-30', 'West Ruislip - Hainault');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-O-35', 'Ealing Broadway - Hainault');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-I-43', 'Epping - West Ruislip');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-I-54', 'Epping - Ealing Broadway');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-I-63', 'Grange Hill - West Ruislip');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-I-66', 'Hainault - Ealing Broadway');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-I-77', 'Hainault - West Ruislip');
insert into Section(_id, name) values('RS_1-CEN-_-y05-670103-I-83', 'Hainault - Ealing Broadway');
insert into Section(_id, name) values('RS_1-CIR-_-y05-290103-O-8', 'Barking - Edgware Road');
insert into Section(_id, name) values('RS_1-CIR-_-y05-290103-O-11', 'Edgware Road - Barking');
insert into Section(_id, name) values('RS_1-CIR-_-y05-290103-O-13', 'Earl''s Court - Aldgate');
insert into Section(_id, name) values('RS_1-CIR-_-y05-290103-I-20', 'Edgware Road - Earl''s Court');
insert into Section(_id, name) values('RS_1-CIR-_-y05-290103-O-22', 'Hammersmith (Ham & City Line) - Barking');
insert into Section(_id, name) values('RS_1-CIR-_-y05-290103-I-23', 'Moorgate - Hammersmith (Ham & City Line)');
insert into Section(_id, name) values('RS_1-CIR-_-y05-290103-O-27', 'Hammersmith (Ham & City Line) - Aldgate');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-3', 'Ealing Broadway - Upminster');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-9', 'Richmond - Upminster');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-12', 'Wimbledon - Upminster');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-15', 'Kensington (Olympia) - Upminster');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-27', 'Ealing Broadway - High Street Kensington');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-32', 'Richmond - High Street Kensington');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-35', 'Wimbledon - Edgware Road');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-O-40', 'Kensington (Olympia) - Edgware Road');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-I-43', 'Upminster - Ealing Broadway');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-I-46', 'Upminster - Richmond');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-I-49', 'Upminster - Wimbledon');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-I-57', 'High Street Kensington - Ealing Broadway');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-I-61', 'High Street Kensington - Richmond');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-I-65', 'Edgware Road - Wimbledon');
insert into Section(_id, name) values('RS_1-DIS-_-y05-1430113-I-70', 'Edgware Road - Kensington (Olympia)');
insert into Section(_id, name) values('RS_1-HAM-_-y05-290103-O-2', 'Hammersmith (Ham & City Line) - Barking');
insert into Section(_id, name) values('RS_1-HAM-_-y05-290103-I-10', 'Barking - Hammersmith (Ham & City Line)');
insert into Section(_id, name) values('RS_1-JUB-_-y05-120140-O-2', 'Stanmore - Stratford');
insert into Section(_id, name) values('RS_1-JUB-_-y05-120140-I-17', 'Stratford - Stanmore');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-O-4', 'Amersham - Aldgate');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-O-9', 'Chesham - Aldgate');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-O-13', 'Watford Underground Station - Aldgate');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-O-21', 'Uxbridge - Aldgate');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-O-25', 'Chesham - Watford Underground Station');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-I-29', 'Aldgate - Amersham');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-I-32', 'Aldgate - Chesham');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-I-37', 'Aldgate - Watford Underground Station');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-I-43', 'Aldgate - Uxbridge');
insert into Section(_id, name) values('RS_1-MET-_-y05-3330101-I-47', 'Watford Underground Station - Rickmansworth');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-O-8', 'Morden - Mill Hill East');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-I-25', 'Mill Hill East - Morden');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-I-38', 'Mill Hill East - Morden');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-O-52', 'Morden - Mill Hill East');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-I-72', 'High Barnet - Morden');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-O-73', 'Morden - High Barnet');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-O-74', 'Morden - Edgware');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-O-77', 'Morden - High Barnet');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-O-79', 'Morden - Edgware');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-I-88', 'High Barnet - Morden');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-I-89', 'Edgware - Morden');
insert into Section(_id, name) values('RS_1-NTN-_-y05-530103-I-92', 'Edgware - Morden');
insert into Section(_id, name) values('RS_1-PIC-_-y05-500101-O-7', 'Heathrow Terminal 5 - Cockfosters');
insert into Section(_id, name) values('RS_1-PIC-_-y05-500101-O-20', 'Heathrow Terminal 4 - Cockfosters');
insert into Section(_id, name) values('RS_1-PIC-_-y05-500101-O-24', 'Uxbridge - Cockfosters');
insert into Section(_id, name) values('RS_1-PIC-_-y05-500101-I-33', 'Cockfosters - Heathrow Terminals 1-3');
insert into Section(_id, name) values('RS_1-PIC-_-y05-500101-I-41', 'Cockfosters - Heathrow Terminal 5');
insert into Section(_id, name) values('RS_1-PIC-_-y05-500101-I-50', 'Cockfosters - Uxbridge');
insert into Section(_id, name) values('RS_1-VIC-_-y05-350112-O-3', 'Brixton - Walthamstow Central');
insert into Section(_id, name) values('RS_1-VIC-_-y05-350112-I-8', 'Walthamstow Central - Brixton');
insert into Section(_id, name) values('RS_1-WAC-_-y05-60102-O-1', 'Waterloo - Bank');
insert into Section(_id, name) values('RS_1-WAC-_-y05-60102-I-2', 'Bank - Waterloo');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-O-4', 'Tower Gateway - Beckton');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-O-6', 'Bank - Woolwich Arsenal DLR');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-O-12', 'Stratford - Lewisham');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-I-16', 'Beckton - Tower Gateway');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-I-17', 'Woolwich Arsenal DLR - Bank');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-I-20', 'Lewisham - Bank');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-I-23', 'Lewisham - Stratford');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-O-27', 'Bank - Lewisham');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-O-31', 'Stratford International DLR - Beckton');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-O-37', 'Stratford International DLR - Woolwich Arsenal DLR');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-I-42', 'Woolwich Arsenal DLR - Stratford International DLR');
insert into Section(_id, name) values('RS_25-DLR-_-y05-6-I-45', 'Beckton - Stratford International DLR');
insert into Section(_id, name) values('RS_63-TRM-1-y05-1-O-2', 'George Street Tramlink Stop - Elmers End');
insert into Section(_id, name) values('RS_63-TRM-1-y05-1-I-3', 'Elmers End - West Croydon Tram Stop');
insert into Section(_id, name) values('RS_63-TRM-2-y05-1-O-1', 'George Street Tramlink Stop - Beckenham Junction');
insert into Section(_id, name) values('RS_63-TRM-2-y05-1-O-2', 'Therapia Lane Tramlink Stop - Beckenham Junction');
insert into Section(_id, name) values('RS_63-TRM-2-y05-1-I-3', 'Beckenham Junction - West Croydon Tram Stop');
insert into Section(_id, name) values('RS_63-TRM-2-y05-1-I-4', 'Beckenham Junction - Therapia Lane Tramlink Stop');
insert into Section(_id, name) values('RS_63-TRM-3-y05-1-O-1', 'Wimbledon - New Addington Tramlink Stop');
insert into Section(_id, name) values('RS_63-TRM-3-y05-1-I-4', 'New Addington Tramlink Stop - Wimbledon');
insert into Section(_id, name) values('RS_63-TRM-4-y05-1-O-1', 'Therapia Lane Tramlink Stop - Elmers End');
insert into Section(_id, name) values('RS_63-TRM-4-y05-1-I-2', 'Elmers End - Therapia Lane Tramlink Stop');
insert into Section(_id, name) values('RS_71-CAB-d-y05-1-O-1', 'Emirates Greenwich Peninsula - Emirates Royal Docks');
insert into Section(_id, name) values('RS_71-CAB-d-y05-1-I-2', 'Emirates Royal Docks - Emirates Greenwich Peninsula');
