BEGIN TRANSACTION;
INSERT INTO StopType (_id, name) VALUES(0, 'unknown');
INSERT INTO StopType (_id, name) VALUES(1, 'Underground');
INSERT INTO StopType (_id, name) VALUES(2, 'Overground');
INSERT INTO StopType (_id, name) VALUES(3, 'DLR');
INSERT INTO StopType (_id, name) VALUES(4, 'Tram');
INSERT INTO StopType (_id, name) VALUES(5, 'Bus');
INSERT INTO StopType (_id, name) VALUES(6, 'Coach');
INSERT INTO StopType (_id, name) VALUES(7, 'Taxi');
INSERT INTO StopType (_id, name) VALUES(8, 'Water');
INSERT INTO StopType (_id, name) VALUES(9, 'Cycle');
INSERT INTO StopType (_id, name) VALUES(10, 'Air');
END TRANSACTION;

BEGIN TRANSACTION;
INSERT INTO Line (_id, name) VALUES(0, 'unknown');
INSERT INTO Line (_id, name) VALUES(1, 'Bakerloo');
INSERT INTO Line (_id, name) VALUES(2, 'Central');
INSERT INTO Line (_id, name) VALUES(3, 'Circle');
INSERT INTO Line (_id, name) VALUES(4, 'District');
INSERT INTO Line (_id, name) VALUES(5, 'HammersmithAndCity');
INSERT INTO Line (_id, name) VALUES(6, 'Jubilee');
INSERT INTO Line (_id, name) VALUES(7, 'Metropolitan');
INSERT INTO Line (_id, name) VALUES(8, 'Northern');
INSERT INTO Line (_id, name) VALUES(9, 'Piccadilly');
INSERT INTO Line (_id, name) VALUES(10, 'Victoria');
INSERT INTO Line (_id, name) VALUES(11, 'WaterlooAndCity');
INSERT INTO Line (_id, name) VALUES(12, 'DLR');
INSERT INTO Line (_id, name) VALUES(13, 'Overground');
INSERT INTO Line (_id, name) VALUES(14, 'Tram');
INSERT INTO Line (_id, name) VALUES(15, 'EmiratesAirline');
END TRANSACTION;
