name: "🔨 Build & Verify"
on:
  workflow_call

jobs:

  build:
    name: "build"
    timeout-minutes: 30

    permissions:
      # actions/checkout
      contents: read
      # EnricoMi/publish-unit-test-result-action -> https://github.com/EnricoMi/publish-unit-test-result-action#permissions
      checks: write

    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash

    steps:

      - name: "Set up Java for Android SDK."
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Temporarily until Android SDK Platform-Tools updates post 34.0.4 in ubuntu-latest.
      # https://github.com/actions/runner-images/blob/ubuntu22/20231016.1/images/linux/Ubuntu2204-Readme.md#android
      - name: "Set up Android SDK."
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Set up Java for Gradle."
        uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: temurin

      - name: "Set up Gradle."
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: "Download TfL Data."
        run: |
          curl --silent --show-error --location --remote-name \
              https://github.com/TWiStErRob/net.twisterrob.travel/releases/download/v1.0.0/LULDLRRiverTramCable.zip
          mkdir -p data/feed15/LULDLRRiverTramCable
          unzip LULDLRRiverTramCable.zip 'tfl_*-*-_-y05-*.xml' -d data/feed15/LULDLRRiverTramCable

      - name: "Build project."
        run: >
          ./gradlew
          --no-daemon
          --stacktrace
          --continue
          build
          :web:status-history:appengineStage

      - name: "Upload 'Unit Test Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Unit Test Results'
          if-no-files-found: error
          path: ${{ github.workspace }}/**/build/reports/tests/*/

      - name: "Upload 'Android Lint Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Android Lint Results'
          if-no-files-found: error
          path: ${{ github.workspace }}/**/build/reports/lint-results*

      - name: "Publish 'Unit Results' check suite."
        if: ${{ success() || failure() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: '🔔 Test: Unit Results'
          comment_mode: off
          report_individual_runs: true
          action_fail_on_inconclusive: true
          test_changes_limit: 0
          junit_files: ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml

      - name: "Upload 'APKs' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'APKs'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/**/build/outputs/apk/
            ${{ github.workspace }}/**/build/outputs/mapping/
            ${{ github.workspace }}/**/build/outputs/logs/
            ${{ github.workspace }}/**/build/outputs/sdk-dependencies/
