name: "CI"

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:

  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@2989567ffe57e907ee08bb907f566bed46e98199 # v1

  build:
    name: "🔨 Build & Verify"
    needs: validate
    uses: ./.github/workflows/CI-build.yml
